theme:
title:
name:
logo: img/jesswein_min.jpg
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Markus Jesswein]
description: [Earth Analytics Data Science Stundent Portfolio]
